### ISSUE TITLE
Support for InteractionApplicationCommandCallbackData flags

### ISSUE THREAD

**Issue by janine9vn** [LiBa001/discord-interactions.py#9]
With the [March 5th changelog](https://discord.com/developers/docs/change-log#march-5-2021), The InteractionApplicationCommandCallbackData now supports the flags. When set to `64` it supports ephemeral messages.

It would be nice if the InteractionApplicationCommandCallbackData in this library could be updated to support this new feature.

I'm happy to contribute the PR if you'd like.

**Comment by LiBa001** [comment]
I already started to implement that on the dev branch ( 3dd35d631161d1aba584c0db83de6d4ab60cd24b ). However, I still need to further test things there.

**Comment by LiBa001** [comment]
With the release of v0.0.7 the changes are now on PyPI and you are encouraged to test them and report possible bugs! :sweat_smile:
